name: pagnostasmng
description: A task manager for android.
publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  neubrutalism_ui: ^1.0.0
  shared_preferences: ^2.2.1
  provider: ^6.0.5
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.3
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/

flutter_launcher_icons:
  android: ic_launcher
  ios: true
  image_path: assets/icon.png

flutter_native_splash:
  color: "#ffffff"
  background_color: "#ffffff"
  image: assets/icon.png
  web: false